namespace SpriteKind {
    export const 魔王 = SpriteKind.create()
    export const 老婆發射物 = SpriteKind.create()
    export const 鈴鐺 = SpriteKind.create()
}
sprites.onOverlap(SpriteKind.Player, SpriteKind.老婆發射物, function (sprite, otherSprite) {
    otherSprite.destroy(effects.coolRadial, 100)
    scene.cameraShake(1, 100)
    info.changeLifeBy(-1)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile6`, function (sprite, location) {
    info.setLife(5)
})
sprites.onOverlap(SpriteKind.Projectile, SpriteKind.魔王, function (sprite, otherSprite) {
    sprite.destroy()
    老婆婆的生命 += -1
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    小精靈.vy = -150
    小精靈.setImage(img`
        ................................
        ................................
        ................................
        ................................
        ..............bbb...............
        ............b53335b.............
        ...........b3355533b............
        ..........3d33333333d...........
        ..........3dd3dddd3dd...........
        .........b33dd1dd1dd3b..........
        .........3333d3dd3d333..........
        ........b3333dddddd333b.........
        ........3333b1dddd1b333.........
        .......b333bd111111db33b........
        .......bbbbdd555111ddb33b.......
        ......3...ddd1111115ddbbb.......
        .........ddd111111555ddd.3......
        .......dddd11111151155dddd......
        .......dd.1155111111111.dd......
        .........555115111111111........
        ........51111111111111115.......
        .........5111111111111155.......
        ..........55555111555555........
        .............dd555dd............
        .............dd...dd............
        .............dd...dd............
        .............bd...db............
        ..............b...b.............
        ................................
        ................................
        `)
    controller.configureRepeatEventDefaults(1000, 1000)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile`, function (sprite, location) {
    info.changeLifeBy(-1)
    scene.cameraShake(2, 100)
})
scene.onOverlapTile(SpriteKind.Food, img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    f f . . . . . . . . . . . 5 . . 
    . f f . . . . . . . . . . 5 5 . 
    . . f f 5 5 5 5 5 5 5 5 5 5 5 5 
    . f f . . . . . . . . . . 5 5 . 
    f f . . . . . . . . . . . 5 . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    `, function (sprite, location) {
    重明夢魘.destroy(effects.ashes, 100)
})
scene.onOverlapTile(SpriteKind.Projectile, assets.image`重明夢魘`, function (sprite, location) {
    金箭攻擊.destroy(effects.ashes, 100)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile20`, function (sprite, location) {
    info.changeLifeBy(0)
    scene.cameraShake(2, 100)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.魔王, function (sprite, otherSprite) {
    老婆婆的生命 = 15
    scene.cameraShake(3, 500)
    tiles.setWallAt(tiles.getTileLocation(3000, 1), true)
    tiles.setWallAt(tiles.getTileLocation(3100, 2), true)
    tiles.setWallAt(tiles.getTileLocation(3000, 3), true)
    while (老婆婆的生命 != 0) {
        pause(1000)
        重明夢魘 = sprites.createProjectileFromSide(assets.image`重明夢魘`, randint(-100, 100), randint(-100, 100))
        重明夢魘.setKind(SpriteKind.老婆發射物)
        重明夢魘.setImage(assets.image`重明夢魘`)
        重明夢魘.setFlag(SpriteFlag.BounceOnWall, true)
    }
})
controller.B.onEvent(ControllerButtonEvent.Pressed, function () {
    金箭攻擊 = sprites.create(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        f f . . . . . . . . . . . 5 . . 
        . f f . . . . . . . . . . 5 5 . 
        . . f f 5 5 5 5 5 5 5 5 5 5 5 5 
        . f f . . . . . . . . . . 5 5 . 
        f f . . . . . . . . . . . 5 . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, SpriteKind.Projectile)
    金箭攻擊 = sprites.createProjectileFromSprite(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        f f . . . . . . . . . . . 5 . . 
        . f f . . . . . . . . . . 5 5 . 
        . . f f 5 5 5 5 5 5 5 5 5 5 5 5 
        . f f . . . . . . . . . . 5 5 . 
        f f . . . . . . . . . . . 5 . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, 小精靈, 300, 0)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile8`, function (sprite, location) {
    game.showLongText("按住\"A\"即可存檔", DialogLayout.Center)
    if (controller.A.isPressed()) {
        if (game.ask("是否存檔")) {
            小精靈.setPosition(1630, 90)
            info.setLife(5)
        }
    }
})
info.onLifeZero(function () {
    if (game.ask("   是否重新開始", "")) {
        if (controller.A.isPressed()) {
            info.setLife(5)
            小精靈.setPosition(11, 110)
        }
    } else {
        if (controller.B.isPressed()) {
            小精靈.setPosition(1630, 90)
            info.setLife(5)
        }
    }
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile27`, function (sprite, location) {
    game.showLongText("老太婆要出現了!", DialogLayout.Top)
    music.setVolume(20)
    music.bigCrash.play()
    小精靈.setPosition(2900, 110)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    otherSprite.destroy(effects.ashes, 0)
    scene.cameraShake(3, 100)
    info.changeLifeBy(-1)
})
let 小烏鴉: Sprite = null
let 金箭攻擊: Sprite = null
let 重明夢魘: Sprite = null
let 老婆婆的生命 = 0
let 小精靈: Sprite = null
小精靈 = sprites.create(img`
    ................................
    ................................
    ................................
    ................................
    ..............bbb...............
    ............b53335b.............
    ...........b3355533b............
    ..........3d33333333d...........
    ..........3dd3dddd3dd...........
    .........b33dd1dd1dd3b..........
    .........3333d3dd3d333..........
    ........b3333dddddd333b.........
    ........3333b1dddd1b333.........
    .......b333bd111111db33b........
    .......bbbbdd555111ddb33b.......
    ......3...ddd1111115ddbbb.......
    .........ddd111111555ddd.3......
    .......dddd11111151155dddd......
    .......dd.1155111111111.dd......
    .........555115111111111........
    ........51111111111111115.......
    .........5111111111111155.......
    ..........55555111555555........
    .............dd555dd............
    .............dd...dd............
    .............dd...dd............
    .............bd...db............
    ..............b...b.............
    ................................
    ................................
    `, SpriteKind.Player)
animation.runImageAnimation(
小精靈,
assets.animation`myAnim0`,
200,
true
)
controller.moveSprite(小精靈, 100, 0)
scene.cameraFollowSprite(小精靈)
小精靈.ay += 200
小精靈.setPosition(11, 110)
tiles.setTilemap(tilemap`背景`)
info.setLife(5)
let 老婆婆 = sprites.create(img`
    ................................................................
    ................................................................
    ................................................................
    .........................................................ccc....
    ....................................................ccacccc.....
    ................................................acccccaccc......
    .............................................cccacccccacc.......
    .........................................cacccccacccccaa........
    .......................................cccaacccccaccccca........
    ....................................cccccccaaccccaaaac..........
    .................................cccccccccccaaccccccc...........
    ................................cccccccccccccaaaaaaaa...........
    ..............................ccccaaaaacccccccccccccc...........
    ............................aaaccacccccaaccccccaaaccccc.........
    ...........................accaccaccccccaccccaaccaaaccccc.......
    ..........................caccaccacccccaacccacccccccaccccc......
    .......................ccccacaccacccccaccccaccccccccacccccc.....
    .....................ccccccacaccacaaaacccccaccccaaaaaccccccc....
    ...................cccccccaaaaaaaaaccccccccaaaaacccccccccccccc..
    ..................aaaaaaaaafffffffaaaaaaaaaaacccccccccccccccccc.
    ..........................ffffffffffffffffaaaaccccccccccccccccc.
    .........................ffddccccddddddddddfffaaaaaacccccccaaaa.
    .........................fffddddcccdddddcccccdfffffaaaaaaaaa....
    ........................ffffdddddddddddccdddddddddddff..........
    .....................fffffffdddd11ddddddd11dddddddddfff.........
    ....................ffffffffddddaadddddddaaddddddddffff.........
    ...................ffcfffffffddddaddbddbddaddddddddfffff........
    ...................fcfcffffffdddddddbddbddddddddddffffffff......
    ...................fcfffccffffbbbdddbdbbddddddbbddfffffffff.....
    ...................ffccccffcffddbdddbbbdddddbbbddffffffffff.....
    ....................fffffcffffddbbddddddcddbbddddffffffccfff....
    ........................ffffffdddbdddddccddbddddffffccfffffff...
    .........................fffffdddddcccccddddddddffcffccffcfff...
    ...............................ddddddddddddddd.fffffffccccfff...
    ................................dddddddddddd...ffcffffffffff....
    .................................dbddddbdd.....ffff..ffffff.....
    .a................................dbbbbdd.......................
    .aa...............................fdddddf.......................
    ..a.............................ffffdddfffffff..................
    ..aa..........................fffffffffffffffff.................
    ...aa.......................fffffffffffffffffffff...............
    ....a......................fffffffffffffffffffffff..............
    ....aa......bbbbbf........ffffffffffffffffffffffffff............
    .....aadd..bbbbbbf........fffffffffffffffffffffffffff...........
    ......aadd.bffffbff......ffffffffffffffffffffffffffff...........
    ......daddddffffbfff....ffffffffffffffffffffffffffffff..........
    ......dddddddfffbffff..ffffffffffffffffffffffffffffffff.........
    .......dddddddffbffffffffffffffffffffffffffffffffffffff.........
    .......ddddddddfbffffffffffffffffffffffffffffffffffffff.........
    ........dddddddbbfffffffffffffffffffffffffffffffffffffff........
    .......bfddddddbffffffffffffffffffffffffffffffffffffffff........
    .......bffdddddbffffffffffffffffffffffffffffffffffffffff........
    .......bfffddbbfffffffffffffffffffffffffffffffcffffffffff.......
    .......bffffdbfffffffffffffffffffffffffffffffcfffffffffff.......
    .......bbfffbbfffffffffffffff.fffffffffffffffcfffffffffff.......
    .......fbbbbbffffffffffffff...fffffffffffffccffffffffffff.......
    ........ffffffffffffffffff....ffffffffffffcfffffffffffff........
    ............ffffffffffff.....ffffffffffffcffffffffffffff........
    ..............fffffffff......ffffffffffcffffffffffffffff........
    .............................fffffffffcffffffffffffffff.........
    .............................fffffccccfffffffffffffffff.........
    .............................ffffbbfffffffffffffffffcf..........
    .............................fffbbbbfffffffffffffffcf...........
    ............................ffffbffbbffffffffffffffc............
    ............................ffffbfffbfffffffffffffcf............
    ............................ffffbfffbbfffffffffffcff............
    ...........................fffffbfdddbffffffffffcfff............
    ...........................fffffdddddbfffffffffcffff............
    ...........................ffffddddddbfffffffffcffff............
    ...........................fffdddddddbbfffffffcfffff............
    ...........................ffddddddddbbffffffcffffff............
    ..........................fffddddddddbbffffccffffffff...........
    ..........................ffffddddddffbfffcffffffffff...........
    ..........................ffffffffbbffbffcfffffffffff...........
    ..........................fffffffffbbfbccffffffffffff...........
    .........................ffffffffffffbbcffffffffffffff..........
    .........................fffffffffffffffffffffffffffff..........
    .........................fffffffffffffffffffffffffffff..........
    ........................fffffffffffffffffffffffffffffff.........
    ........................fffffffffffffffffffffffffffffff.........
    ........................fffffffffffffffffffffffffffffff.........
    ........................fffffffffffffffffffffffffffffff.........
    .......................ffffffffffffffffffffffffffffffff.........
    .......................fffffffffffffffffffffffffffffffff........
    .......................fffffffffffffffffffffffffffffffff........
    .......................fffffffffffffffffffffffffffffffff........
    .............................ffffffffffffffffffffffffffff.......
    .............................ffffff...fffffffffffffffffff.......
    .............................ffffff..........fffffffffffff......
    .............................fffffff.........ffffff.............
    .............................fffffff.........fffffff............
    .............................fffffff.........fffffff............
    .....................ff......fffffff.........fffffff............
    .....................ff......fffffff..ff.....fffffff............
    .....................fff....ffffffff..ff.....fffffff............
    .....................fffffffffffffff..fff...ffffffff............
    .....................fffffffffffffff..fffffffffffff.............
    ......................fffffffffffff...fffffffffffff.............
    ......................fffffffffff......fffffffffff..............
    ............................ffff............fffff...............
    `, SpriteKind.魔王)
animation.runImageAnimation(
老婆婆,
assets.animation`myAnim1`,
200,
true
)
老婆婆.setPosition(3100, 80)
老婆婆的生命 = 1000000
for (let index = 0; index < 1; index++) {
    music.setTempo(150)
    music.playTone(185, music.beat(BeatFraction.Half))
    music.playTone(196, music.beat(BeatFraction.Half))
    music.playTone(208, music.beat(BeatFraction.Half))
    music.playTone(220, music.beat(BeatFraction.Half))
    music.playTone(233, music.beat(BeatFraction.Half))
    music.playTone(247, music.beat(BeatFraction.Half))
}
pause(200)
game.showLongText("森林遭受黑暗氣息入侵", DialogLayout.Top)
game.showLongText("需打敗黑烏牙鳥老太婆", DialogLayout.Top)
game.showLongText("森林才能恢復原來的美好", DialogLayout.Top)
game.showLongText("以下幾點在路途中要注意:", DialogLayout.Top)
game.splash("1.遇到障礙物需要跳過 ")
game.splash("2.飛行的小烏牙鳥及重明夢惡會扣一顆心", "")
game.splash("3.地頭毒蛇會直接死亡")
game.splash("4.小兔兔可回滿血")
game.splash("5.看不見的黑魔法牆需要跳過")
game.splash("6.魚昆可以記錄重生點(死亡時按B即可)")
game.splash("7.要先觸及黑烏牙鳥老太婆才可攻擊，可發動技能擊殺老太婆")
game.onUpdate(function () {
    if (老婆婆的生命 == 0) {
        老婆婆.startEffect(effects.fire)
        老婆婆.destroy(effects.disintegrate, 500)
        game.over(true, effects.starField)
    }
})
game.onUpdateInterval(2000, function () {
    for (let index = 0; index < 1; index++) {
        if (Math.percentChance(95)) {
            小烏鴉 = sprites.create(assets.tile`myTile4`, SpriteKind.Enemy)
            小烏鴉.setPosition(10, 24)
            小烏鴉.ax += 30
        }
    }
})
forever(function () {
    music.setTempo(200)
    music.playTone(262, music.beat(BeatFraction.Whole))
    music.playTone(196, music.beat(BeatFraction.Whole))
    music.playTone(262, music.beat(BeatFraction.Whole))
    music.playTone(277, music.beat(BeatFraction.Whole))
    music.playTone(208, music.beat(BeatFraction.Whole))
    music.playTone(277, music.beat(BeatFraction.Whole))
    music.playTone(294, music.beat(BeatFraction.Whole))
    music.playTone(220, music.beat(BeatFraction.Whole))
    music.playTone(294, music.beat(BeatFraction.Whole))
    music.playTone(277, music.beat(BeatFraction.Double))
    music.playTone(277, music.beat(BeatFraction.Whole))
})
